version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: facebook-bot-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: facebook-bot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - facebook-bot-network

  # Facebook Bot Application
  app:
    build: .
    container_name: facebook-bot-app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/facebook-bot?authSource=admin
      CLIENT_URL: http://localhost:3000
      JWT_SECRET: your-super-secret-jwt-key-here
      FACEBOOK_APP_ID: your-facebook-app-id
      FACEBOOK_APP_SECRET: your-facebook-app-secret
      FACEBOOK_REDIRECT_URI: http://localhost:3000/auth/facebook/callback
      WEBHOOK_VERIFY_TOKEN: your-webhook-verify-token
      SERVER_URL: http://localhost:5000
    ports:
      - "5000:5000"
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./server/logs:/app/server/logs
      - ./uploads:/app/uploads
    networks:
      - facebook-bot-network

volumes:
  mongodb_data:

networks:
  facebook-bot-network:
    driver: bridge

